=== AlexisVennegas/FP-DUAL/Lenguaje de marcas/Xpath/videojuegos/videoJuegos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="videojuegos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="videojuego" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" />
                            <xs:element name="genero" type="xs:string" />
                            <xs:element name="unidades-vendidas" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="anyo" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AlexisVennegas/FP-DUAL/Lenguaje de marcas/Xpath/videojuegos/videoJuegos.xml
<?xml version="1.0" encoding="UTF-8"?>
<videojuegos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="videoJuegos.xsd">
        <videojuego anyo="2011">
        <titulo>Minecraft</titulo>
        <genero>Sandbox</genero>
        <unidades-vendidas>176000000</unidades-vendidas>
    </videojuego>
        <videojuego anyo="1984">
        <titulo>Tetris</titulo>
        <genero>Puzle</genero>
        <unidades-vendidas>170000000</unidades-vendidas>
    </videojuego>
        <videojuego anyo="2013">
        <titulo>Grand Theft Auto 5</titulo>
        <genero>Sandbox</genero>
        <unidades-vendidas>110000000</unidades-vendidas>
    </videojuego>
        <videojuego anyo="1985">
        <titulo>Super Mario Bros</titulo>
        <genero>Plataformas</genero>
        <unidades-vendidas>48000000</unidades-vendidas>
        </videojuego>
</videojuegos>
