=== AlexisVennegas/FP-DUAL/Lenguaje de marcas/XML/2/e/empleados.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empleados">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ficha" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="telefono" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="edad" type="xs:integer"/>
                        </xs:sequence>
                        <xs:attribute name="numero" type="xs:integer" use="required"/>
                    </xs:complexType>

                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AlexisVennegas/FP-DUAL/Lenguaje de marcas/XML/2/e/empleados.xml
<?xml version="1.0" encoding="UTF-8"?>
<empleados
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="empleados.xsd">
    <ficha numero="1">
       <nombre telefono="914824023">María José Pérez</nombre>
        <edad>22</edad>
    </ficha>
    <ficha numero="2">
        <nombre telefono="652142214">Pablo Gil Paz</nombre>
        <edad>23</edad>
    </ficha>
    <ficha numero="3">
        <nombre telefono="962140056">Paula Moreno Serrano</nombre>
        <edad>23</edad>
    </ficha>
</empleados>
