=== AlexisVennegas/FP-DUAL/Lenguaje de marcas/XML/PRACTICA EXAMEN/Universidad/universidad.dtd
<!ELEMENT universidad (alumno+)>
<!ELEMENT alumno (nombre, carrera, nota)>
<!ATTLIST alumno matricula CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT carrera (#PCDATA)>
<!ELEMENT nota (#PCDATA) >

=== AlexisVennegas/FP-DUAL/Lenguaje de marcas/XML/PRACTICA EXAMEN/Universidad/universidad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE universidad SYSTEM "universidad.dtd" > -->
<universidad
    xmlns:xsi="http://www.w3.org/2001/XMLSchema"
    xsi:noNamespaceSchemaLocation="universidad.xsd"
>
    
    <alumno matricula="ALU1234">
        <nombre>Carlos</nombre>
        <carrera>Informatica</carrera>
        <nota>8.5</nota>
    </alumno>

    <alumno matricula="ALU5678">
        <nombre>Maria</nombre>
        <carrera>Matematicas</carrera>
        <nota>9.2</nota>
    </alumno>

</universidad>
